#!/usr/bin/env sh

dir=$1
rec=$2
shredd=$(which shred)

for file in $(ls $dir/*.tgz); do
  gpg -e --armor --always-trust --batch --yes -r $rec $file
  # Wipe out your copy of key.bin  
  if [ -z "$shredd" ]; then
    openssl rand -base64 900000 > $file
    echo 0 > $file
    cp /dev/null $file
  else
    shred -v -n 25 -u -z $file
  fi
  rm -f $file 2>/dev/null
done
